// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Data;

#nullable disable

namespace OnlineStoreApp.Migrations
{
    [DbContext(typeof(MyAppContext))]
    [Migration("20260629052438_StartSet")]
    partial class StartSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineStoreApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("OnlineStoreApp.Models.Client", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("Phone")
                        .HasColumnType("bigint");

                    b.HasKey("Name", "Address");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Name = "John Doe",
                            Address = "123 Main St",
                            Phone = 1234567890L
                        },
                        new
                        {
                            Name = "Jane Smith",
                            Address = "456 Elm St",
                            Phone = 9876543210L
                        });
                });

            modelBuilder.Entity("OnlineStoreApp.Models.Item", b =>
                {
                    b.Property<string>("Serial")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ClientAddress")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("Serial");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClientName", "ClientAddress");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("OnlineStoreApp.Models.Item", b =>
                {
                    b.HasOne("OnlineStoreApp.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId");

                    b.HasOne("OnlineStoreApp.Models.Client", "Client")
                        .WithMany("Items")
                        .HasForeignKey("ClientName", "ClientAddress");

                    b.Navigation("Category");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("OnlineStoreApp.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineStoreApp.Models.Client", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
